### ISSUE TITLE
Add a Github Actions workflow to run the test suite on every pull request to main

### ISSUE THREAD

**Issue by chriscarrollsmith** [Promptly-Technologies-LLC/llm_classifier#5]
The workflow must:

- Checkout the branch
- Install uv and Python
- Install dependencies with `uv sync`
- Run the tests with `uv run pytest`
- Run mypy with `uv run mypy .`

E.g.,

```yaml
name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install project
        run: uv sync

      - name: Run type checking with mypy
        run: uv run mypy .

      - name: Run tests with pytest
        run: uv run pytest tests/
```
